services:
  web:
    build:
      context: docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  php:
    build:
      context: docker/dev/php
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=1
      - PHP_IDE_CONFIG=serverName=shorty

  db:
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
