apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.volume.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.volume.class }}
  resources:
    requests:
      storage: {{ .Values.mysql.volume.requests.storage }}
