apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
spec:
  selector:
    app: {{ .Values.nginx.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.servicePort }}
      targetPort: {{ .Values.nginx.container.port }}
  type: ClusterIP
