apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.servicePort }}
      targetPort: {{ .Values.mysql.container.port }}
  type: ClusterIP
